### ISSUE TITLE
[FEAT] 3차 세미나 과제

### ISSUE THREAD

**Issue by hyeon-z** [30th-THE-SOPT-Server-Part/HyunJi#5]
## 📌 Feature Issue
- 오늘 세미나에서 나온 코드들 직접 타이핑 하면서 익혀보기
- 오늘 세미나 실습 폴더 내부에 Blog.ts Model 을 만들고 CRUD 완성하기

## 📝 To-do

🌼 실천과제

- [x] 견고한 Node.js 프로젝트 설계
- [x] CRUD 실습

🌻 발전과제

- [x] [POST] /blog
- [x] [PUT] /blog/:postId
- [x] [GET] /blog/:postId
- [x] [DELETE] /blog/:postId
